import { Menu } from "@/componentes/Menu";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Livro } from "@/classes/modelo/Livro";
import { LinhaLivro } from "@/componentes/LivroLinha";

const LivroLista: NextPage = () => { 
    
    const baseURL = "http://localhost:3000/api/livros"
    
    const [livros,setLivros] = useState([])
    const [carregado,setCarregado] = useState(false)
    
    useEffect( () => {
        obterLivros().then(()=>{
            setCarregado(true)
        })
    },[carregado])
    
    
    const obter = async () => {
        const info = await fetch(baseURL)
        const livros = await info.json()
        return livros
    }
    
    const excluirLivro = async (codigo:number) => {
        const del = fetch(baseURL + `/${codigo}`,{method: "DELETE"})
    }
    
    const obterLivros = async () =>{
        const lista = await obter()
        setLivros(lista)
    }
    
    const excluir = async( codigo: number) => {
        const del = excluirLivro(codigo)
        setCarregado(false)
    }
    
    return (
        <div>
            <Head>
                <title>Loja Next</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favcon.ico" />
            </Head>
            <Menu/>
            <main>
                <div className="container py-3">

                <h1 className="h1">Catálogo de Livros</h1>
                <table className="table">
                <thead className="table-dark">
                    <tr>
                        <th scope="col"> Título </th>
                        <th scope="col"> Resumo </th>
                        <th scope="col"> Editora </th>
                        <th scope="col"> Autores </th>
                    </tr>
                </thead>
                <tbody className="table-striped"> 
                    {livros.map( (livro:Livro, index:number) => {
                        return ( <LinhaLivro key={index} livro={livro} excluir={excluir}></LinhaLivro>)
                    })}
                </tbody>
                </table>
                    </div>
            </main>
        </div>
    )}
    
export default LivroLista